[project]
name = "c"
version = "1.0.0"
dependencies = [
    "d"
]
requires-python = ">=3.11"

[tool.uv.sources]
d = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
