[project]
name = "d"
dynamic=["version"]
dependencies = [
    "anyio>=4.0.0,<5"
]
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../__about__.py"