[project]
name = "e"
dynamic=["version"]
dependencies = [
    "numpy>=2.0.0,<3"
]
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../__about__.py"
